plugins:
  discourse_multisite_email_enabled:
    default: false
  discourse_multisite_email_smtp_authentication_mode:
    default: "plain"
  discourse_multisite_email_smtp_address:
    default: "172.17.0.1"
  discourse_multisite_email_smtp_port:
    default: 587
    min: 0
    max: 65537
  discourse_multisite_email_smtp_username:
    default: "username@example.com"
  discourse_multisite_email_smtp_password:
    default: "password"
    secret: true
